"""
Django settings for project01 project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from datetime import timedelta
from pathlib import Path
import sys


# 项目路径
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# 安全设置
SECRET_KEY = 'django-insecure-2z@9yu4os+hhx^cij+9sdk2$!86^jtsfhacgv-im1f2+l%qu7f'
DEBUG = True
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # 添加 DRF
    'corsheaders',  # 允许跨域
    'rest_framework_simplejwt',
    'account',  # 账户应用
    'Comparison',  # 资产分析应用
]


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # 令牌有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # 刷新令牌有效期
    'ROTATE_REFRESH_TOKENS': False,  # 是否旋转刷新令牌
    'BLACKLIST_AFTER_ROTATION': True,  # 是否黑名单旋转后的刷新令牌
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'your_secret_key',  # 用于加密签名
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'USER_ID_FIELD': 'userid',  # 用户的唯一标识字段
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 允许跨域
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StockManager_Backendcode.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StockManager_Backendcode.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
}

# 跨域配置，允许所有前端访问
CORS_ALLOW_ALL_ORIGINS = True

from pymongo import MongoClient
from datetime import datetime
client = MongoClient('mongodb://81.68.81.245:27017/mydatabase?authSource=admin')
db = client['admin']  # 使用 admin 数据库


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # 或者 'django.contrib.sessions.backends.cached_db'

# 迅投量化配置
XT_CONFIG = {
    # 用户指定的迅投路径（优先使用）
    'USERDATA_PATH': r'E:\迅投极速交易终端 睿智融科版\userdata',
    
    # 备用路径列表，按优先级排序
    'USERDATA_PATHS': [
        r'E:\迅投极速交易终端 睿智融科版\userdata',  # 用户指定的实际路径
        r'E:\迅投极速交易终端睿智融科版\userdata',   # 备用路径
        r'D:\迅投极速交易终端 睿智融科版\userdata',
        r'D:\迅投极速交易终端睿智融科版\userdata',
        r'C:\迅投极速交易终端 睿智融科版\userdata',
        r'C:\迅投极速交易终端睿智融科版\userdata',
        # 其他可能的路径
        r'E:\迅投极速交易终端\userdata',
        r'D:\迅投极速交易终端\userdata',
        r'C:\迅投极速交易终端\userdata',
        r'F:\迅投极速交易终端 睿智融科版\userdata',
        r'F:\迅投极速交易终端睿智融科版\userdata',
        r'F:\迅投极速交易终端\userdata',
        r'G:\迅投极速交易终端 睿智融科版\userdata',
        r'G:\迅投极速交易终端睿智融科版\userdata',
        r'G:\迅投极速交易终端\userdata',
        # 用户个人目录的可能路径
        os.path.join(os.path.expanduser('~'), 'AppData', 'Local', '迅投极速交易终端', 'userdata'),
        os.path.join(os.path.expanduser('~'), 'AppData', 'Local', '迅投极速交易终端 睿智融科版', 'userdata'),
        os.path.join(os.path.expanduser('~'), 'AppData', 'Local', '迅投极速交易终端睿智融科版', 'userdata'),
        os.path.join(os.path.expanduser('~'), 'Documents', '迅投极速交易终端', 'userdata'),
        os.path.join(os.path.expanduser('~'), 'Documents', '迅投极速交易终端 睿智融科版', 'userdata'),
        os.path.join(os.path.expanduser('~'), 'Documents', '迅投极速交易终端睿智融科版', 'userdata'),
    ],
    
    # API配置信息
    'API_KEY': os.getenv('XT_API_KEY', ''),
    'SECRET_KEY': os.getenv('XT_SECRET_KEY', ''),
    
    # 用户提供的连接token
    'TOKEN': os.getenv('XT_TOKEN', 'cc409ba91553c061681dc279daa42e498cae374d'),
    
    # 迅投数据中心地址列表
    'ADDR_LIST': [
        '115.231.218.73:55310',
        '115.231.218.79:55310',
        '218.16.123.11:55310',
        '218.16.123.27:55310'
    ],
    
    # 数据服务端口
    'PORT': 58601,
    
    # 连接超时设置
    'TIMEOUT': 30,
    
    # 是否启用调试模式
    'DEBUG': True
}
