# Generated by Django 5.2.4 on 2025-08-30 05:49

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                (
                    "phone",
                    models.CharField(max_length=11, unique=True, verbose_name="手机号"),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="昵称"),
                ),
                ("avatar", models.URLField(blank=True, verbose_name="头像")),
                (
                    "is_new_user",
                    models.BooleanField(default=True, verbose_name="是否新用户"),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("inactive", "非活跃"),
                            ("suspended", "暂停"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="账户状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="最后登录时间"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "account_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="手机号")),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="是否已使用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("expire_at", models.DateTimeField(verbose_name="过期时间")),
            ],
            options={
                "verbose_name": "验证码",
                "verbose_name_plural": "验证码",
                "db_table": "account_verification_code",
                "indexes": [
                    models.Index(
                        fields=["phone", "created_at"],
                        name="account_ver_phone_8c380a_idx",
                    ),
                    models.Index(
                        fields=["expire_at"], name="account_ver_expire__2176f4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField(verbose_name="访问令牌")),
                ("refresh_token", models.TextField(verbose_name="刷新令牌")),
                (
                    "token_type",
                    models.CharField(
                        default="Bearer", max_length=20, verbose_name="令牌类型"
                    ),
                ),
                (
                    "expires_in",
                    models.IntegerField(default=3600, verbose_name="过期时间(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户令牌",
                "verbose_name_plural": "用户令牌",
                "db_table": "account_user_token",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="account_use_user_id_adbbef_idx",
                    ),
                    models.Index(
                        fields=["access_token"], name="account_use_access__d245c9_idx"
                    ),
                ],
            },
        ),
    ]
