# Generated by Django 4.2.23 on 2025-09-21 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CacheIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20, verbose_name="股票代码")),
                ("period", models.CharField(max_length=10, verbose_name="周期")),
                ("start_date", models.DateField(verbose_name="起始日期")),
                ("end_date", models.DateField(verbose_name="结束日期")),
                (
                    "file_path",
                    models.CharField(max_length=255, verbose_name="文件路径"),
                ),
                (
                    "last_access",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="最后访问时间"
                    ),
                ),
                ("size_bytes", models.BigIntegerField(verbose_name="文件大小")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "缓存索引",
                "verbose_name_plural": "缓存索引",
                "indexes": [
                    models.Index(
                        fields=["symbol", "period"],
                        name="Comparison__symbol_dec7cd_idx",
                    ),
                    models.Index(
                        fields=["last_access"], name="Comparison__last_ac_40a0f1_idx"
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="Comparison__start_d_a8827b_idx",
                    ),
                ],
                "unique_together": {("symbol", "period", "start_date", "end_date")},
            },
        ),
    ]
